### ISSUE TITLE
retry policy 

### ISSUE THREAD

**Issue by azmym** [spring-guides/gs-messaging-gcp-pubsub#12]
How can implement try policy for pubsub subscription , I have implemented application to collect some messages from pubsub and suddenly i got the following error and stream stopped !!
```
c.g.c.p.v.StreamingSubscriberConnection - terminated streaming with exception 
com.google.api.gax.rpc.PermissionDeniedException: io.grpc.StatusRuntimeException: PERMISSION_DENIED: User not authorized to perform this action.
at com.google.api.gax.rpc.ApiExceptionFactory.createException(ApiExceptionFactory.java:55)
 at com.google.cloud.pubsub.v1.StreamingSubscriberConnection$1.onFailure(StreamingSubscriberConnection.java:237)
 at com.google.common.util.concurrent.Futures$CallbackListener.run(Futures.java:1365)
 at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
 at com.google.common.util.concurrent.AbstractFuture.executeListener(AbstractFuture.java:973)
 at com.google.common.util.concurrent.AbstractFuture.complete(AbstractFuture.java:821)
 at com.google.common.util.concurrent.AbstractFuture.setException(AbstractFuture.java:685)
 at com.google.common.util.concurrent.SettableFuture.setException(SettableFuture.java:54)
 at com.google.cloud.pubsub.v1.StreamingSubscriberConnection$StreamingPullResponseObserver.onError(StreamingSubscriberConnection.java:173)
 at io.grpc.stub.ClientCalls$StreamObserverToCallListenerAdapter.onClose(ClientCalls.java:419)
 at io.grpc.ForwardingClientCallListener.onClose(ForwardingClientCallListener.java:41)
 at io.grpc.internal.CensusStatsModule$StatsClientInterceptor$1$1.onClose(CensusStatsModule.java:684)
 at io.grpc.ForwardingClientCallListener.onClose(ForwardingClientCallListener.java:41)
 at io.grpc.internal.CensusTracingModule$TracingClientInterceptor$1$1.onClose(CensusTracingModule.java:392)
 at io.grpc.internal.ClientCallImpl.closeObserver(ClientCallImpl.java:475)
 at io.grpc.internal.ClientCallImpl.access$300(ClientCallImpl.java:63)
 at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl.close(ClientCallImpl.java:557)
 at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl.access$600(ClientCallImpl.java:478)
 at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1StreamClosed.runInContext(ClientCallImpl.java:590)
 at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37)
 at io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:123)
 at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
 at java.util.concurrent.FutureTask.run(FutureTask.java:266)
 at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
 at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
 at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
 at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
 at java.lang.Thread.run(Thread.java:745)
Caused by: io.grpc.StatusRuntimeException: PERMISSION_DENIED: User not authorized to perform this action.
 at io.grpc.Status.asRuntimeException(Status.java:526)
 ... 19 common frames omitted
```

**Comment by joaoandremartins** [comment]
@azmym feel free to post issues like this in our project's issue tracker at https://github.com/spring-cloud/spring-cloud-gcp/issues.

Your question is not really related to retrying. Did you provide suitable credentials, either through the `spring.cloud.gcp.credentials.location` property, or through the application-default credentials (`gcloud auth application-default login`)?

**Comment by azmym** [comment]
@joaoandremartins I already provided the credential and the application was working fine for 1 month,
but seem one of the administration change the privilege for some reason , Now I need to avoid this issue in future if that happened again i need the service retry to connect again after certain time, is that possible ?

**Comment by joaoandremartins** [comment]
@azmym looking at the [`Subscriber`](https://github.com/GoogleCloudPlatform/google-cloud-java/blob/master/google-cloud-clients/google-cloud-pubsub/src/main/java/com/google/cloud/pubsub/v1/Subscriber.java) API, it doesn't look like that is specifiable.

But I'm also not sure how valid that use case is (i.e., service account being deleted/modified to stop having correct rights).

You would need to implement that kind of retry on your side, by catch that exception and then acting accordingly (e.g., creating another `Subscriber` with different permissions? that is pretty much the user's choice).

**Comment by azmym** [comment]
@joaoandremartins this error out of my hand, it is occur in spring framework, my code handling start after receive the message  
```
@ServiceActivator(inputChannel = "pubsubInputChannel")
    public void messageReceiver(Message<String> message) {
    try{
          // some business logic
    }catch(Exception e){
    }    
}
```

```
@Bean
    public MessageChannel pubsubInputChannel() {
        return new DirectChannel();
    }

    @Bean
    public PubSubInboundChannelAdapter messageChannelAdapter(
            @Qualifier("pubsubInputChannel") MessageChannel inputChannel, PubSubTemplate pubSubTemplate) throws InterruptedException, ExecutionException, TimeoutException {
        PubSubInboundChannelAdapter adapter =
                new PubSubInboundChannelAdapter(pubSubTemplate, subscriptionName);
        adapter.setOutputChannel(inputChannel);
        adapter.setAckMode(AckMode.MANUAL);
        return adapter;
    }
```

**Comment by joaoandremartins** [comment]
@azmym I'm afraid the solution for this is to implement monitoring in your app and, whenever such an exception is thrown, create a new service account, furnish a new private key and restart your application pointing to the new credentials.
Service accounts stopping to work is definitely not an expected scenario, as far as I know.

**Comment by snicoll** [comment]
Getting started guides aren't the appropriate place to ask questions. Please review the [Reference Guide](https://googlecloudplatform.github.io/spring-cloud-gcp/reference/html/index.html). If that didn't help, StackOverflow or Gitter might help.
