### ISSUE TITLE
Messages not Received after sometime with an Exception thrown.

### ISSUE THREAD

**Issue by rajithavk** [spring-guides/gs-messaging-gcp-pubsub#4]
Hi I'm using this integration for a Google cloud project. 
Everything works fine in the beginning and after sometime when no messages are remaining (idle) following exception gets thrown and any messages to the PubSub are no longer received by the application. 
```
 2017-10-10 05:06:51.502  WARN [realtime-streaming,,,] 1 --- [pool-2-thread-1] c.g.c.p.v.StreamingSubscriberConnection  : Terminated streaming with exception
 
 io.grpc.StatusRuntimeException: UNAVAILABLE
         at io.grpc.Status.asRuntimeException(Status.java:526) ~[grpc-core-1.6.1.jar!/:1.6.1]
         at io.grpc.stub.ClientCalls$StreamObserverToCallListenerAdapter.onClose(ClientCalls.java:385) ~[grpc-stub-1.6.1.jar!/:1.6.1]
         at io.grpc.internal.ClientCallImpl.closeObserver(ClientCallImpl.java:422) ~[grpc-core-1.6.1.jar!/:1.6.1]
         at io.grpc.internal.ClientCallImpl.access$300(ClientCallImpl.java:61) ~[grpc-core-1.6.1.jar!/:1.6.1]
         at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl.close(ClientCallImpl.java:504) ~[grpc-core-1.6.1.jar!/:1.6.1]
         at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl.access$600(ClientCallImpl.java:425) ~[grpc-core-1.6.1.jar!/:1.6.1]
         at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1StreamClosed.runInContext(ClientCallImpl.java:536) ~[grpc-core-1.6.1.jar!/:1.6.1]
         at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37) ~[grpc-core-1.6.1.jar!/:1.6.1]
         at io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:102) ~[grpc-core-1.6.1.jar!/:1.6.1]
         at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [na:1.8.0_131]
         at java.util.concurrent.FutureTask.run(FutureTask.java:266) [na:1.8.0_131]
         at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180) [na:1.8.0_131]
         at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293) [na:1.8.0_131]
         at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [na:1.8.0_131]
         at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [na:1.8.0_131]
         at java.lang.Thread.run(Thread.java:748) [na:1.8.0_131]
 Caused by: java.io.IOException: Connection reset by peer
         at sun.nio.ch.FileDispatcherImpl.read0(Native Method) ~[na:1.8.0_131]
         at sun.nio.ch.SocketDispatcher.read(SocketDispatcher.java:39) ~[na:1.8.0_131]
         at sun.nio.ch.IOUtil.readIntoNativeBuffer(IOUtil.java:223) ~[na:1.8.0_131]
         at sun.nio.ch.IOUtil.read(IOUtil.java:192) ~[na:1.8.0_131]
         at sun.nio.ch.SocketChannelImpl.read(SocketChannelImpl.java:380) ~[na:1.8.0_131]
         at io.netty.buffer.PooledUnsafeDirectByteBuf.setBytes(PooledUnsafeDirectByteBuf.java:288) ~[netty-buffer-4.1.14.Final.jar!/:4.1.14.Final]
         at io.netty.buffer.AbstractByteBuf.writeBytes(AbstractByteBuf.java:1106) ~[netty-buffer-4.1.14.Final.jar!/:4.1.14.Final]
         at io.netty.channel.socket.nio.NioSocketChannel.doReadBytes(NioSocketChannel.java:372) ~[netty-transport-4.1.14.Final.jar!/:4.1.14.Final]
         at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:123) ~[netty-transport-4.1.14.Final.jar!/:4.1.14.Final]
         at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:645) ~[netty-transport-4.1.14.Final.jar!/:4.1.14.Final]
         at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:580) ~[netty-transport-4.1.14.Final.jar!/:4.1.14.Final]
         at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:497) ~[netty-transport-4.1.14.Final.jar!/:4.1.14.Final]
         at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:459) ~[netty-transport-4.1.14.Final.jar!/:4.1.14.Final]
         at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858) ~[netty-common-4.1.14.Final.jar!/:4.1.14.Final]
         at io.netty.util.concurrent.
```
Here is my POM :

>     <parent>
>         <groupId>org.springframework.boot</groupId>
>         <artifactId>spring-boot-starter-parent</artifactId>
>         <version>1.5.7.RELEASE</version>
>         <relativePath/> 
>     </parent>
> 
>     <properties>
>         <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
>         <project.reporting.outputEncoding>UTF-8</project.reporting.outputEncoding>
>         <java.version>1.8</java.version>
>         <spring-cloud.version>Dalston.SR3</spring-cloud.version>
>     </properties>
> 
>     <dependencies>
> 
>         <dependency>
>             <groupId>org.springframework.boot</groupId>
>             <artifactId>spring-boot-starter-web</artifactId>
>         </dependency>
> 
>         <dependency>
>             <groupId>org.springframework.boot</groupId>
>             <artifactId>spring-boot-starter-test</artifactId>
>             <scope>test</scope>
>         </dependency>
> 
>         
>         <dependency>
>             <groupId>org.springframework.boot</groupId>
>             <artifactId>spring-boot-starter-websocket</artifactId>
>         </dependency>
> 
>         <dependency>
>             <groupId>com.google.code.gson</groupId>
>             <artifactId>gson</artifactId>
>         </dependency>
> 
>         <dependency>
>             <groupId>com.google.guava</groupId>
>             <artifactId>guava</artifactId>
>             <version>21.0</version>
>         </dependency>
> 
>         <dependency>
>             <groupId>org.springframework.cloud</groupId>
>             <artifactId>spring-cloud-starter-kubernetes-all</artifactId>
>             <version>0.2.0.RELEASE</version>
>         </dependency>
> 
> 
>         
>         <dependency>
>             <groupId>org.springframework.boot</groupId>
>             <artifactId>spring-boot-starter-actuator</artifactId>
>             <version>1.5.4.RELEASE</version>
>         </dependency>
> 
>         <dependency>
>             <groupId>org.springframework.cloud</groupId>
>             <artifactId>spring-integration-gcp</artifactId>
>             <version>1.0.0.BUILD-SNAPSHOT</version>
>         </dependency>
> 
>         
>         <dependency>
>             <groupId>org.springframework.cloud</groupId>
>             <artifactId>spring-cloud-gcp-starter-pubsub</artifactId>
>             <version>1.0.0.BUILD-SNAPSHOT</version>
>         </dependency>
> 
> 
>         <dependency>
>             <groupId>com.google.auth</groupId>
>             <artifactId>google-auth-library-credentials</artifactId>
>             <version>0.6.1</version>
>         </dependency>
>         <dependency>
>             <groupId>com.google.auth</groupId>
>             <artifactId>google-auth-library-oauth2-http</artifactId>
>             <version>0.6.1</version>
>         </dependency>
> 
>         
>         <dependency>
>             <groupId>io.grpc</groupId>
>             <artifactId>grpc-netty</artifactId>
>             <version>1.6.1</version>
>         </dependency>
> 
>         <dependency>
>                 <groupId>io.netty</groupId>
>                 <artifactId>netty-tcnative-boringssl-static</artifactId>
>                 <version>2.0.0.Final</version>
>                 <classifier>${os.detected.classifier}</classifier>
>         </dependency>
> 
> 
>         <dependency>
>             <groupId>org.springframework</groupId>
>             <artifactId>spring-websocket</artifactId>
>             <version>4.3.11.RELEASE</version>
>         </dependency>
> 
>         <dependency>
>             <groupId>com.fasterxml.jackson.core</groupId>
>             <artifactId>jackson-databind</artifactId>
>             <version>2.8.10</version>
>         </dependency>
> 
>         <dependency>
>             <groupId>org.projectlombok</groupId>
>             <artifactId>lombok</artifactId>
>             <version>1.16.0</version>
>         </dependency>
> 
> 
>     </dependencies>
> 
>     <dependencyManagement>
>         <dependencies>
>             <dependency>
>                 <groupId>org.springframework.cloud</groupId>
>                 <artifactId>spring-cloud-dependencies</artifactId>
>                 <version>${spring-cloud.version}</version>
>                 <type>pom</type>
>                 <scope>import</scope>
>             </dependency>
> 
>         </dependencies>
>     </dependencyManagement>
> 
>     <repositories>
>         <repository>
>             <id>repository.spring.snapshot</id>
>             <name>Spring Snapshot Repository</name>
>             <url>http://repo.spring.io/snapshot</url>
>         </repository>
> 
>         <repository>
>             <id>central</id>
>             <name>Maven Repository Switchboard</name>
>             <layout>default</layout>
>             <url>http://repo1.maven.org/maven2</url>
>             <snapshots>
>                 <enabled>true</enabled>
>             </snapshots>
>         </repository>
> 
>     </repositories>
> 
>     <build>
>         <plugins>
>             <plugin>
>                 <groupId>org.springframework.boot</groupId>
>                 <artifactId>spring-boot-maven-plugin</artifactId>
>             </plugin>
>         </plugins>
> 
>         <extensions>
>                 <extension>
>         	        <groupId>kr.motd.maven</groupId>
>                 	<artifactId>os-maven-plugin</artifactId>
>                 	<version>1.5.0.Final</version>
> 	        </extension>
>         </extensions>
> 
>     </build>
> 
> </project>

**Comment by artembilan** [comment]
@joaoandremartins , @meltsufin, any thoughts?

>  Caused by: java.io.IOException: Connection reset by peer

Or there is some default policy to reject idle consumers, or we don't have choice unless to implement something like *heartbeat*.

Thanks

**Comment by meltsufin** [comment]
Since we're just a wrapper on top of the Pub/Sub client library, it's likely an issue/question for the client library, and we should file it [there](https://github.com/GoogleCloudPlatform/google-cloud-java/issues) as well.
The closest one I can find there is https://github.com/GoogleCloudPlatform/google-cloud-java/issues/1616, but it was resolved.

**Comment by rajithavk** [comment]
Above references has PR fixing this issue it seems. Therefore closing this here as resolved.

**Comment by meltsufin** [comment]
Frankly, I'm not convinced that the referenced PR fixes the issue because all it does is change the log level of some messages.
As I understand, you're saying that there is an actual functional issue with messages not being received. Is that correct?

**Comment by rajithavk** [comment]
There is. To me it seems like the retry strategy. Latest I observed the logs for a long time and after a long pause messages starts receiving again. But in an actual use case this is problematic, at least it should be configurable. So this new observation suggests that messages are not forever being trapped. So should we open this same issue in this regard or open a new as a suggestion for enhancement ?

**Comment by meltsufin** [comment]
@rajithavk We got a suggestion [here](https://github.com/GoogleCloudPlatform/google-cloud-java/issues/2506#issuecomment-336343187) to try. I think you should reopen this issue because we might have to wait till the next gRPC release to really have a fix.

**Comment by rajithavk** [comment]
@meltsufin sure reopening. I had a look at the suggestion too. Somehow I think there should be a more straightforward fix to this in the long run.

**Comment by joaoandremartins** [comment]
Would it be better to file the issue against our main repo? https://github.com/spring-cloud/spring-cloud-gcp

**Comment by meltsufin** [comment]
Yes! I totally missed the fact that this was in the guides repo.

**Comment by rajithavk** [comment]
#https://github.com/GoogleCloudPlatform/google-cloud-java/pull/2585
